[package]
name = "rvc-architecture-tests"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
serde_json.workspace = true

[dev-dependencies]
observability.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["registry"] }

[[bin]]
name = "generate-architecture-md"
path = "src/bin/generate_architecture_md.rs"
